### ISSUE TITLE
SWPR/ETH

### ISSUE THREAD

**Issue by 0xVenky** [0xVenky/swapr-project#1]
Approve Call  (from SWPR Quick Wallet Scheme)
to 0xecA7F78d59D16812948849663b26FE10E320f80C (Staking Rewards Factory)

value 224000000000000000000000

Create Distribution Call

```
rewardTokensAddresses:
	[0xdE903E2712288A1dA82942DDdF2c20529565aC30]

stakableTokenAddress:
	0xa66b20912cbea522278f3056b4ae60d0d3ee271b

rewardAmounts:
	[224000000000000000000000]

startingTimestamp:
	1633014000

endingTimestamp:
	1634223600

locked:
	false

stakingCap:
		0

```

**Comment by KeenanLukeOM** [comment]
Confirmed reward address, stakable address, reward amount (and approval), both timestamps.
