### ISSUE TITLE
GRT / ETH

### ISSUE THREAD

**Issue by 0xVenky** [0xVenky/swapr-project#10]
Approve Call (from SWPR Quick Wallet Scheme)
to 0xecA7F78d59D16812948849663b26FE10E320f80C (Staking Rewards Factory)

value 13440000000000000000000

Create Distribution Call

```
rewardTokensAddresses:
	[0xdE903E2712288A1dA82942DDdF2c20529565aC30]

stakableTokenAddress:
	0x828ec866fa3c4b2dcd6bbe7f2b5c147514936aa8

rewardAmounts:
	[13440000000000000000000]

startingTimestamp:
	1633014000

endingTimestamp:
	1634223600

locked:
	false

stakingCap:
		0

```

**Comment by KeenanLukeOM** [comment]
Confirmed all

**Comment by 0xVenky** [comment]
https://dxgovernance.github.io/dxvote/#/arbitrum/proposal/0xb0b137395b0a5310ccef16233d362a8714847807387092aeda7f8099531ef48d
