### ISSUE TITLE
GNO / ETH

### ISSUE THREAD

**Issue by 0xVenky** [0xVenky/swapr-project#14]
Approve Call (from SWPR Quick Wallet Scheme)
to 0xecA7F78d59D16812948849663b26FE10E320f80C (Staking Rewards Factory)

value 17920000000000000000000

Create Distribution Call

```
rewardTokensAddresses:
	[0xdE903E2712288A1dA82942DDdF2c20529565aC30]

stakableTokenAddress:
	0x82be2ede715f0bad545ab17a2c2194b5457ef4af

rewardAmounts:
	[17920000000000000000000]

startingTimestamp:
	1633014000

endingTimestamp:
	1634223600

locked:
	false

stakingCap:
		0

```

**Comment by KeenanLukeOM** [comment]
Confirmed all. Verified empty pair address in DXstats.

**Comment by 0xVenky** [comment]
https://dxgovernance.github.io/dxvote/#/arbitrum/proposal/0x5000490b0dd29ed3d3ee3ec93b4c8c29be2c131ed3a35b20aec2f2b8e30202e2

@jpkcambridge @KeenanLukeOM review please before we start voting
