### ISSUE TITLE
DAI / ETH

### ISSUE THREAD

**Issue by 0xVenky** [0xVenky/swapr-project#3]
pair address: 0x19c34e4c477cfe8aa5db564ec2707905409fbe4c

Approve Call (from SWPR Quick Wallet Scheme)
to 0xecA7F78d59D16812948849663b26FE10E320f80C (Staking Rewards Factory)

value 89600000000000000000000

Create Distribution Call

```
rewardTokensAddresses:
	[0xdE903E2712288A1dA82942DDdF2c20529565aC30]

stakableTokenAddress:
	0x19c34e4c477cfe8aa5db564ec2707905409fbe4c

rewardAmounts:
	[89600000000000000000000]

startingTimestamp:
	1633014000

endingTimestamp:
	1634223600

locked:
	false

stakingCap:
		0

```

**Comment by KeenanLukeOM** [comment]
Confirmed all. Confirmed the DAI address and checked pair address directly within DXstats since the pool is empty.
