### ISSUE TITLE
ETH / WBTC

### ISSUE THREAD

**Issue by 0xVenky** [0xVenky/swapr-project#5]
Approve Call (from SWPR Quick Wallet Scheme)
to 0xecA7F78d59D16812948849663b26FE10E320f80C (Staking Rewards Factory)

value 89600000000000000000000

Create Distribution Call

```
rewardTokensAddresses:
	[0xdE903E2712288A1dA82942DDdF2c20529565aC30]

stakableTokenAddress:
	0x9a17d97fb5f76f44604270448ac77d55ac40c15c

rewardAmounts:
	[89600000000000000000000]

startingTimestamp:
	1633014000

endingTimestamp:
	1634223600

locked:
	false

stakingCap:
		0

```

**Comment by KeenanLukeOM** [comment]
Confirmed all

**Comment by 0xVenky** [comment]
https://dxvote-dev.netlify.app/#/arbitrum/proposal/0xb804b56ccbe37ab9c73b64e5e642be721477c38844e4f016afc2e324bd74056d
