### ISSUE TITLE
USDC / USDT

### ISSUE THREAD

**Issue by 0xVenky** [0xVenky/swapr-project#6]
Approve Call (from SWPR Quick Wallet Scheme)
to 0xecA7F78d59D16812948849663b26FE10E320f80C (Staking Rewards Factory)

value 35840000000000000000000

Create Distribution Call

```
rewardTokensAddresses:
	[0xdE903E2712288A1dA82942DDdF2c20529565aC30]

stakableTokenAddress:
	0xed4de839da369ee4c7077b0358e21d9100506d71

rewardAmounts:
	[35840000000000000000000]

startingTimestamp:
	1633014000

endingTimestamp:
	1634223600

locked:
	false

stakingCap:
		0

```

**Comment by KeenanLukeOM** [comment]
Confirmed all

**Comment by 0xVenky** [comment]
https://dxvote-dev.netlify.app/#/arbitrum/proposal/0x0ce1e8dbbabb023fdc2823a42ce1e739f1c16bd69ee1468ed0f7fe23cb848b70
