### ISSUE TITLE
DXD / ETH

### ISSUE THREAD

**Issue by 0xVenky** [0xVenky/swapr-project#7]
Approve Call (from SWPR Quick Wallet Scheme)
to 0xecA7F78d59D16812948849663b26FE10E320f80C (Staking Rewards Factory)

value 44800000000000000000000

Create Distribution Call

```
rewardTokensAddresses:
	[0xdE903E2712288A1dA82942DDdF2c20529565aC30]

stakableTokenAddress:
	0x9f6524b4b2e0984ca1de6654efae6c81b3e08046

rewardAmounts:
	[44800000000000000000000]

startingTimestamp:
	1633014000

endingTimestamp:
	1634223600

locked:
	false

stakingCap:
		0

```

**Comment by KeenanLukeOM** [comment]
Confirmed all.

**Comment by 0xVenky** [comment]
https://dxvote-dev.netlify.app/#/arbitrum/proposal/0xde373e8fa02d306f1ce4a15104d840adfb818522803a7e98ff6fc947aa9dfe5a
