### ISSUE TITLE
CRV / ETH

### ISSUE THREAD

**Issue by 0xVenky** [0xVenky/swapr-project#8]
Approve Call (from SWPR Quick Wallet Scheme)
to 0xecA7F78d59D16812948849663b26FE10E320f80C (Staking Rewards Factory)

value 26880000000000000000000

Create Distribution Call

```
rewardTokensAddresses:
	[0xdE903E2712288A1dA82942DDdF2c20529565aC30]

stakableTokenAddress:
	0xd45c3a746a22016b2ac77210bdc1cbde2b1aeee6

rewardAmounts:
	[26880000000000000000000]

startingTimestamp:
	1633014000

endingTimestamp:
	1634223600

locked:
	false

stakingCap:
		0

```

**Comment by KeenanLukeOM** [comment]
Confirmed all.

**Comment by 0xVenky** [comment]
https://dxgovernance.github.io/dxvote/#/arbitrum/proposal/0xb96bed9b23ba131d4a7439d935656105cc3c74d46cb8ceba576f1bd869def5bd
