### ISSUE TITLE
MKR / ETH

### ISSUE THREAD

**Issue by 0xVenky** [0xVenky/swapr-project#9]
Approve Call (from SWPR Quick Wallet Scheme)
to 0xecA7F78d59D16812948849663b26FE10E320f80C (Staking Rewards Factory)

value 13440000000000000000000

Create Distribution Call

```
rewardTokensAddresses:
	[0xdE903E2712288A1dA82942DDdF2c20529565aC30]

stakableTokenAddress:
	0x87af02682454bea3b9cc4d9b4138aaa379506c31

rewardAmounts:
	[13440000000000000000000]

startingTimestamp:
	1633014000

endingTimestamp:
	1634223600

locked:
	false

stakingCap:
		0

```

**Comment by KeenanLukeOM** [comment]
Confirmed all. 

Pair is super weird for some reason? Must be a MKR function of some kind, the weird token being shown in the UI points directly to the actual token contract and previous farm functioning as intended :

0x2e9a6df78e42a30712c10a9dc4b1c8656f8f2879 

vs

https://arbiscan.io/token/0x2e9a6df78e42a30712c10a9dc4b1c8656f8f2879?a=0x87af02682454bea3b9cc4d9b4138aaa379506c31

As shown in pair contract:

![image](https://user-images.githubusercontent.com/76129769/134981152-ad8f8f69-56dd-4b1a-832d-f0910863e0d9.png)
